import { getSlides } from "../helpers";
import { TSlide } from "../types";

export const getCQRSSlides = (id: string, left: string, right: string): TSlide[] => {
  const texts = [
    `
# CQRS

### Goal: segregate R/W operations into separate data models

- Command represents an operations that alters the state of the system, don't return data
- Query represents an operation that retrieves data, don't alter the state of the system
`,
    `
# Why CQRS?
- Different models for R/W = optimize each side independently
- Different tech for R/W = use the best tools
- Scalability: R/W workloads can be scaled independently
- Performance: read models can be denormalized or optimized for specific query patterns
- Write models can focus on business logic, validation and consistency
`,
    `
# Challenges
- Synch R/W models (**Consistency**): use *Event Driven architecture* and update read models based on events generated by write models 
- Handle Write Concurrency: use *optimistic locking* (e.g. version, timestamps...) to detect and resolve conflicts (e.g. pull and retry)
- Additional infrastructure: use *Microservices architecture* and scale each side independently as required
`,
    `
# Consistency
- Any architecture may lead to temporary inconsistencies between R/W models: **Eventual Consistency** 
- Design your system to handle it and relax the *consistency* requirements for all the Read Models that can tolerate it 
- Useful patterns to synchronize data between R/W: Full-duplex messaging (e.g. Websockets), Pub/Sub, Polling, CDC...
`,
    `
# Example: Consistency tradeoff
### Architecture: CQRS + Event Sourcing
- *Event Sourcing*: **PUB** all changes as a sequence of events in an *Event Store*
- Read Models **SUB** to Event Store streams to be updated
- SSE / Websockets / Polling to get updates from Read Models to user screens
`,
    `
## Eventual Consistency (I)
### Real Time
- Some read models must be updated in Real Time
- Instead of SUB to the Event Store, read model may SUB to a lower level event-bus / message broker
- May lead to temporary inconsistencies between R/W models: "read model updated, write is not yet"
-- But you get real time updates!
`,
    `
## Eventual Consistency (II)
### Latency Tolerance
- Some read models don't need "ASAP" updates
- Instead of SUB to the Event Store, read model may be updated using Polling
- May lead to temporary inconsistencies between R/W models: "write model updated, read is not yet" 
-- But you don't invest resources to update read model when it is not needed!
`,
    `
# Useful links
- CQRS [pattern I](https://martinfowler.com/bliki/CQRS.html)
- CQRS [pattern II](https://microservices.io/patterns/data/cqrs.html)
- CQRS [pattern III](https://docs.microsoft.com/en-us/azure/architecture/patterns/cqrs)
- Martin Dilger [book](https://leanpub.com/eventmodeling-and-eventmodeling)
`,
  ]

  return getSlides(texts, id, right, left);
}